/*
Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	core "github.com/gardener/gardener/pkg/apis/core"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeShootEvents implements ShootEventInterface
type FakeShootEvents struct {
	Fake *FakeCore
	ns   string
}

var shooteventsResource = schema.GroupVersionResource{Group: "core.gardener.cloud", Version: "", Resource: "shootevents"}

var shooteventsKind = schema.GroupVersionKind{Group: "core.gardener.cloud", Version: "", Kind: "ShootEvent"}

// Get takes name of the shootEvent, and returns the corresponding shootEvent object, and an error if there is any.
func (c *FakeShootEvents) Get(name string, options v1.GetOptions) (result *core.ShootEvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(shooteventsResource, c.ns, name), &core.ShootEvent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*core.ShootEvent), err
}

// List takes label and field selectors, and returns the list of ShootEvents that match those selectors.
func (c *FakeShootEvents) List(opts v1.ListOptions) (result *core.ShootEventList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(shooteventsResource, shooteventsKind, c.ns, opts), &core.ShootEventList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &core.ShootEventList{ListMeta: obj.(*core.ShootEventList).ListMeta}
	for _, item := range obj.(*core.ShootEventList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested shootEvents.
func (c *FakeShootEvents) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(shooteventsResource, c.ns, opts))

}

// Create takes the representation of a shootEvent and creates it.  Returns the server's representation of the shootEvent, and an error, if there is any.
func (c *FakeShootEvents) Create(shootEvent *core.ShootEvent) (result *core.ShootEvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(shooteventsResource, c.ns, shootEvent), &core.ShootEvent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*core.ShootEvent), err
}

// Update takes the representation of a shootEvent and updates it. Returns the server's representation of the shootEvent, and an error, if there is any.
func (c *FakeShootEvents) Update(shootEvent *core.ShootEvent) (result *core.ShootEvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(shooteventsResource, c.ns, shootEvent), &core.ShootEvent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*core.ShootEvent), err
}

// Delete takes name of the shootEvent and deletes it. Returns an error if one occurs.
func (c *FakeShootEvents) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(shooteventsResource, c.ns, name), &core.ShootEvent{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeShootEvents) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(shooteventsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &core.ShootEventList{})
	return err
}

// Patch applies the patch and returns the patched shootEvent.
func (c *FakeShootEvents) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *core.ShootEvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(shooteventsResource, c.ns, name, pt, data, subresources...), &core.ShootEvent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*core.ShootEvent), err
}
